language: php

php:
  - 5.4

node_js:
  - "0.11"

mysql:
  database: dkan_travis 
  username: root
  encoding: utf8

install:
  - npm install
  - composer install
  - mysql -e 'create database drupal_travis;'
  - sudo apt-get update > /dev/null
  - sudo apt-get --quiet=2 install php5-cgi php5-curl php5-gd php5-mysql > /dev/null

# Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:6.*


before_script:
  # Install Drupal 
  - git clone --branch 7.x --depth 1 http://git.drupal.org/project/drupal.git
  - cd drupal 
  - drush si --sites-subdir=default --db-url=mysql://root:@127.0.0.1/drupal_travis --account-name=admin --account-pass=admin  --site-name="Drupal"  --yes
  - drush cc all --yes
  - drush dis overlay --yes
  - drush --quiet --yes --root=$PWD --server=builtin runserver :8888 > /dev/null 2>&1 &
  - sleep 4s

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - cd ../

  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
  - java -jar selenium-server-standalone-2.35.0.jar -quiet -p 4444 -log shut_up_selenium &
  - sleep 5

script:
  - bin/behat
